version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      - DB_USER=secret
      - DB_PASSWORD=secret
      - DB_NAME=dutydb
      - NODE_ENV=live
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    command: npx nodemon src/server.ts

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dutydb
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start
